import Link from "next/link";
import { ArrowRight, BadgeCheck, Clock3, Coins, Gauge, Globe2, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const features = [
  { icon: Zap, title: "Nomor tersedia cepat", text: "Pilih layanan, negara, provider, dan operator melalui alur pembelian yang ringkas." },
  { icon: ShieldCheck, title: "Transaksi aman", text: "Harga dihitung ulang di server, saldo memakai ledger, dan transaksi dilindungi idempotency." },
  { icon: MessageSquareText, title: "OTP terpantau", text: "Status diperbarui melalui backend tanpa mengekspos API key provider ke browser." },
];
const steps = ["Pilih aplikasi", "Pilih negara dan operator", "Konfirmasi harga", "Terima nomor dan OTP"];
const faqs = [
  ["Apakah OTPMarket bagian dari RumahOTP?", "Tidak. OTPMarket adalah aplikasi mandiri yang menggunakan RumahOTP sebagai penyedia API."],
  ["Bagaimana harga ditentukan?", "Harga jual dihitung dari harga modal terbaru ditambah aturan keuntungan yang dikelola admin."],
  ["Bagaimana cara deposit?", "Permintaan deposit diarahkan ke WhatsApp super admin dan saldo ditambahkan setelah pembayaran diverifikasi."],
  ["Apakah layanan boleh dipakai untuk apa saja?", "Tidak. Layanan hanya boleh digunakan untuk aktivitas yang sah dan sesuai ketentuan platform terkait."],
];

export default function HomePage() {
  return <main>
    <header className="sticky top-0 z-40 border-b bg-[var(--background)]/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-3 font-black"><span className="grid size-10 place-items-center rounded-xl bg-indigo-600 text-white"><ShieldCheck className="size-5"/></span><span>{process.env.APP_NAME ?? "OTPMarket"}</span></Link><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#cara-kerja">Cara kerja</a><a href="#keunggulan">Keunggulan</a><a href="#faq">FAQ</a></nav><div className="flex gap-2"><Button asChild variant="ghost"><Link href="/login">Masuk</Link></Button><Button asChild><Link href="/register">Daftar</Link></Button></div></div></header>
    <section className="grid-bg relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(99,102,241,.22),transparent_35%)]"/><div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><span className="inline-flex items-center gap-2 rounded-full border bg-[var(--card)] px-4 py-2 text-sm font-bold text-indigo-600"><Sparkles className="size-4"/> Platform OTP profesional</span><h1 className="text-balance mt-7 text-5xl font-black leading-[1.05] tracking-tight md:text-7xl">Nomor virtual dan OTP dalam satu dashboard yang aman.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted-foreground)]">Kelola pembelian nomor, pemantauan OTP, saldo, riwayat transaksi, dan deposit dengan pengalaman SaaS yang cepat dan transparan.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/register">Mulai sekarang <ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline"><Link href="/login">Buka dashboard</Link></Button></div><div className="mt-10 grid max-w-xl grid-cols-3 gap-3 text-center"><div><p className="text-2xl font-black">5/10s</p><p className="text-xs text-[var(--muted-foreground)]">Rate limit aman</p></div><div><p className="text-2xl font-black">24/7</p><p className="text-xs text-[var(--muted-foreground)]">Status terpantau</p></div><div><p className="text-2xl font-black">IDR</p><p className="text-xs text-[var(--muted-foreground)]">Harga transparan</p></div></div></div>
    <Card className="relative overflow-hidden border-indigo-500/30"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-indigo-600 via-violet-500 to-cyan-500"/><CardContent className="p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-[var(--muted-foreground)]">Saldo tersedia</p><p className="mt-1 text-3xl font-black">Rp125.000</p></div><div className="rounded-2xl bg-indigo-500/10 p-4 text-indigo-500"><Coins className="size-7"/></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[var(--muted)] p-4"><p className="text-xs text-[var(--muted-foreground)]">Pesanan aktif</p><p className="mt-2 text-xl font-black">2 nomor</p></div><div className="rounded-2xl bg-[var(--muted)] p-4"><p className="text-xs text-[var(--muted-foreground)]">Berhasil bulan ini</p><p className="mt-2 text-xl font-black">48 order</p></div></div><div className="mt-6 space-y-3">{["WhatsApp — Indonesia", "Telegram — Malaysia", "Facebook — Indonesia"].map((name,i)=><div key={name} className="flex items-center justify-between rounded-xl border p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-indigo-500/10 font-black text-indigo-500">{i+1}</span><div><p className="font-bold">{name}</p><p className="text-xs text-[var(--muted-foreground)]">Siap digunakan</p></div></div><BadgeCheck className="size-5 text-emerald-500"/></div>)}</div></CardContent></Card></div></section>
    <section id="keunggulan" className="mx-auto max-w-7xl px-5 py-24"><div className="mx-auto max-w-2xl text-center"><p className="font-bold uppercase tracking-[.2em] text-indigo-500">Keunggulan</p><h2 className="mt-3 text-4xl font-black">Dibangun untuk transaksi yang dapat dipercaya</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><Card key={title}><CardContent className="p-7"><div className="grid size-12 place-items-center rounded-xl bg-indigo-500/10 text-indigo-500"><Icon className="size-6"/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-[var(--muted-foreground)]">{text}</p></CardContent></Card>)}</div></section>
    <section id="cara-kerja" className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-5"><div className="grid gap-12 lg:grid-cols-2"><div><p className="font-bold uppercase tracking-[.2em] text-indigo-300">Cara kerja</p><h2 className="mt-3 text-4xl font-black">Empat langkah sederhana menuju OTP.</h2><p className="mt-5 text-slate-300">Semua komunikasi RumahOTP berjalan di server. Browser hanya menerima data yang sudah disanitasi.</p></div><div className="grid gap-4 sm:grid-cols-2">{steps.map((step,i)=><div key={step} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-sm font-black text-indigo-300">0{i+1}</span><p className="mt-3 font-bold">{step}</p></div>)}</div></div><div className="mt-14 grid gap-4 md:grid-cols-4">{[[LockKeyhole,"API key server-only"],[Clock3,"Polling terpusat"],[Gauge,"Rate limiter global"],[Globe2,"Responsif semua perangkat"]].map(([Icon,label])=>{const C=Icon as typeof LockKeyhole; return <div key={String(label)} className="flex items-center gap-3 rounded-xl bg-white/5 p-4"><C className="size-5 text-indigo-300"/><span className="text-sm font-semibold">{String(label)}</span></div>})}</div></div></section>
    <section id="faq" className="mx-auto max-w-5xl px-5 py-24"><div className="text-center"><p className="font-bold uppercase tracking-[.2em] text-indigo-500">FAQ</p><h2 className="mt-3 text-4xl font-black">Pertanyaan yang sering diajukan</h2></div><div className="mt-10 space-y-4">{faqs.map(([q,a])=><details key={q} className="surface rounded-2xl p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 leading-7 text-[var(--muted-foreground)]">{a}</p></details>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24"><div className="rounded-3xl bg-indigo-600 px-6 py-14 text-center text-white md:px-16"><h2 className="text-4xl font-black">Siap membeli nomor pertama Anda?</h2><p className="mx-auto mt-4 max-w-xl text-indigo-100">Buat akun, isi saldo melalui super admin, lalu gunakan layanan dari dashboard.</p><Button asChild className="mt-7 bg-white text-indigo-700 hover:bg-indigo-50" size="lg"><Link href="/register">Daftar gratis</Link></Button></div></section>
    <footer className="border-t"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 md:grid-cols-4"><div className="md:col-span-2"><p className="font-black">{process.env.APP_NAME ?? "OTPMarket"}</p><p className="mt-3 max-w-md text-sm leading-6 text-[var(--muted-foreground)]">Layanan nomor virtual dan OTP untuk penggunaan yang sah. Tidak berafiliasi atau meniru merek RumahOTP.</p></div><div><p className="font-bold">Legal</p><div className="mt-3 space-y-2 text-sm text-[var(--muted-foreground)]"><Link href="/terms" className="block">Syarat & ketentuan</Link><Link href="/privacy" className="block">Kebijakan privasi</Link></div></div><div><p className="font-bold">Dukungan</p><div className="mt-3 space-y-2 text-sm text-[var(--muted-foreground)]"><a href="https://wa.me/6282141218134" className="block">WhatsApp admin</a><a href="mailto:support@example.com" className="block">Email dukungan</a></div></div></div></footer>
  </main>;
}
