import Link from "next/link";
import { CheckCircle2, CircleDollarSign, Clock3, ReceiptText, ShoppingCart, Wallet } from "lucide-react";
import { requireUser } from "@/lib/auth/guards";
import { prisma } from "@/lib/db";
import { formatRupiah } from "@/lib/money";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { Button } from "@/components/ui/button";
import { SectionCard } from "@/components/section-card";
import { DataTable } from "@/components/data-table";
import { StatusBadge } from "@/components/status-badge";

export default async function DashboardPage(){const user=await requireUser();const [orders,total,success,active,ledgers]=await Promise.all([prisma.otpOrder.findMany({where:{userId:user.id},take:5,orderBy:{createdAt:"desc"}}),prisma.otpOrder.aggregate({where:{userId:user.id},_sum:{sellingPrice:true},_count:true}),prisma.otpOrder.count({where:{userId:user.id,status:{in:["OTP_RECEIVED","COMPLETED"]}}}),prisma.otpOrder.count({where:{userId:user.id,status:{in:["ORDERING","WAITING_OTP","OTP_RECEIVED"]}}}),prisma.balanceLedger.findMany({where:{userId:user.id},take:5,orderBy:{createdAt:"desc"}})]);return <><PageHeader title="Dashboard" description="Ringkasan saldo, pesanan, dan aktivitas terbaru Anda." action={<Button asChild><Link href="/dashboard/buy-number"><ShoppingCart className="size-4"/>Beli nomor</Link></Button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Saldo pengguna" value={formatRupiah(user.balance?.balance??0n)} icon={Wallet}/><StatCard title="Total transaksi" value={String(total._count)} icon={ReceiptText}/><StatCard title="Pesanan aktif" value={String(active)} icon={Clock3}/><StatCard title="Pesanan berhasil" value={String(success)} icon={CheckCircle2}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><SectionCard title="Pesanan terbaru" description="Lima transaksi terakhir"><DataTable headers={["Order","Layanan","Harga","Status","Tanggal"]} rows={orders.map(o=>[<Link key={o.id} className="font-bold text-indigo-500" href={`/dashboard/orders/${o.id}`}>{o.internalOrderNumber}</Link>,o.serviceName,formatRupiah(o.sellingPrice),<StatusBadge key={`${o.id}-s`} status={o.status}/>,new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(o.createdAt)])}/></SectionCard><SectionCard title="Aktivitas saldo" description="Mutasi terbaru"><div className="space-y-3">{ledgers.map(l=><div key={l.id} className="flex justify-between rounded-xl border p-3"><div><p className="text-sm font-bold">{l.description}</p><p className="text-xs text-[var(--muted-foreground)]">{l.type}</p></div><p className={`font-bold ${l.credit>0n?"text-emerald-600":"text-red-600"}`}>{l.credit>0n?"+":"-"}{formatRupiah(l.credit>0n?l.credit:l.debit)}</p></div>)}</div></SectionCard></div><div className="mt-6 grid gap-4 md:grid-cols-3"><StatCard title="Pengeluaran total" value={formatRupiah(total._sum.sellingPrice??0n)} icon={CircleDollarSign}/><StatCard title="OTP diterima" value={String(success)} icon={CheckCircle2}/><StatCard title="Waktu server" value="Asia/Jakarta" icon={Clock3}/></div></>}
